import { Project, PaymentRecord, Contractor, ContractorAssignment } from './types'

export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'PACサイト移行お見積り',
    client_name: '一般財団法人ありがとうインターナショナル',
    status: '見積もり中',
    probability: '確度（中）',
    amount: 175000,
    tax_amount: 17500,
    period: '第3期',
    invoice_month: null,
    payment_month: null,
    notes: null,
    estimate_url: null,
    invoice_url: null,
    parent_id: null,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: '2',
    name: 'ありがとうインターナショナル運用保守4・5月',
    client_name: '一般財団法人ありがとうインターナショナル',
    status: '見積もり中',
    probability: '確定',
    amount: 20000,
    tax_amount: 2000,
    period: '第3期',
    invoice_month: '2025年5月',
    payment_month: null,
    notes: null,
    estimate_url: null,
    invoice_url: null,
    parent_id: null,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: '3',
    name: 'ORIBE公式サイト構築',
    client_name: 'UNIWORKS',
    status: '見積もり中',
    probability: '保留・トラブル有り',
    amount: 2437500,
    tax_amount: 243750,
    period: '第3期',
    invoice_month: null,
    payment_month: null,
    notes: null,
    estimate_url: null,
    invoice_url: null,
    parent_id: null,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: '4',
    name: 'マイナビ様パートナーページ作成',
    client_name: '株式会社マイナビ',
    status: '見積もり中',
    probability: '確度（中）',
    amount: 750000,
    tax_amount: 75000,
    period: '第3期',
    invoice_month: null,
    payment_month: null,
    notes: null,
    estimate_url: null,
    invoice_url: null,
    parent_id: null,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: '5',
    name: 'ハリッチLPミニリッチプラスLP実装作業',
    client_name: '株式会社caroa',
    status: '進行中',
    probability: '確定',
    amount: 87500,
    tax_amount: 8750,
    period: '第4期',
    invoice_month: '2025年6月',
    payment_month: '2025年7月',
    notes: null,
    estimate_url: null,
    invoice_url: null,
    parent_id: null,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: '6',
    name: 'ME CAMPUSコーディング',
    client_name: 'PKSHA株式会社',
    status: '完了済',
    probability: '確定',
    amount: 850000,
    tax_amount: 85000,
    period: '第3期',
    invoice_month: '2024年11月',
    payment_month: '2024年12月',
    notes: null,
    estimate_url: null,
    invoice_url: null,
    parent_id: null,
    created_at: '2024-10-01',
    updated_at: '2024-12-01',
  },
  {
    id: '7',
    name: 'Eiko Planning Shopify構築（実装）',
    client_name: '株式会社マイナビ',
    status: '進行中',
    probability: '確度（中）',
    amount: 1500000,
    tax_amount: 150000,
    period: '第3期',
    invoice_month: null,
    payment_month: null,
    notes: null,
    estimate_url: null,
    invoice_url: null,
    parent_id: null,
    created_at: '2025-01-01',
    updated_at: '2025-01-01',
  },
  {
    id: '8',
    name: 'KIRINヘルスサイエンスダイレクト',
    client_name: 'UNIWORKS',
    status: '請求済み',
    probability: '確定',
    amount: 5625000,
    tax_amount: 562500,
    period: '第3期',
    invoice_month: '2025年3月',
    payment_month: '2025年4月',
    notes: null,
    estimate_url: null,
    invoice_url: null,
    parent_id: null,
    created_at: '2024-12-01',
    updated_at: '2025-03-01',
  },
  {
    id: '9',
    name: 'カトリ_STUDIO年間利用料',
    client_name: '株式会社カトリ',
    status: '立て替え',
    probability: '確定',
    amount: 12982,
    tax_amount: 1298,
    period: '第4期',
    invoice_month: '2024年11月',
    payment_month: '2024年12月',
    notes: '11/22更新',
    estimate_url: null,
    invoice_url: null,
    parent_id: null,
    created_at: '2024-11-01',
    updated_at: '2024-11-22',
  },
  {
    id: '10',
    name: '双日建材株式会社MOISSサイト制作',
    client_name: '株式会社マイナビ',
    status: '見積もり中',
    probability: '確度（高）',
    amount: 1475000,
    tax_amount: 147500,
    period: '第3期',
    invoice_month: null,
    payment_month: null,
    notes: null,
    estimate_url: null,
    invoice_url: null,
    parent_id: null,
    created_at: '2025-02-01',
    updated_at: '2025-02-01',
  },
]

export const mockPaymentRecords: PaymentRecord[] = [
  {
    id: '1',
    project_id: '6',
    project_name: 'ME CAMPUSコーディング',
    client_name: 'PKSHA株式会社',
    payment_date: '2024-12-15',
    amount: 935000,
    payment_month: '2024年12月',
    period: '第3期',
    created_at: '2024-12-15',
  },
  {
    id: '2',
    project_id: '9',
    project_name: 'カトリ_STUDIO年間利用料',
    client_name: '株式会社カトリ',
    payment_date: '2024-12-22',
    amount: 14280,
    payment_month: '2024年12月',
    period: '第3期',
    created_at: '2024-12-22',
  },
  {
    id: '3',
    project_id: '8',
    project_name: 'KIRINヘルスサイエンスダイレクト',
    client_name: 'UNIWORKS',
    payment_date: '2025-04-15',
    amount: 6187500,
    payment_month: '2025年4月',
    period: '第4期',
    created_at: '2025-04-15',
  },
]

export const mockContractors: Contractor[] = [
  {
    id: '1',
    skills: ['コーディング', 'WordPress'],
    company_name: 'EUREKA DESIGN STUDIO',
    contact_name: '川松直樹',
    invoice_status: '登録済み',
    email: 'naoki.kawmt2u@gmail.com',
    phone: '080-3434-6658',
    notes: null,
    created_at: '2024-01-01',
  },
  {
    id: '2',
    skills: ['エンジニアリング', 'AI'],
    company_name: 'AKエンジニアリング',
    contact_name: '勝井明仁',
    invoice_status: '免税事業者',
    email: null,
    phone: null,
    notes: null,
    created_at: '2024-01-01',
  },
  {
    id: '3',
    skills: ['デザイン'],
    company_name: '関谷デザイン',
    contact_name: '関谷',
    invoice_status: '申請中',
    email: null,
    phone: null,
    notes: null,
    created_at: '2024-01-01',
  },
  {
    id: '4',
    skills: ['デザイン', 'コーディング'],
    company_name: '木下詩織デザイン事務所',
    contact_name: '木下詩織',
    invoice_status: '未定',
    email: null,
    phone: null,
    notes: null,
    created_at: '2024-01-01',
  },
]

export const mockContractorAssignments: ContractorAssignment[] = [
  {
    id: '1',
    contractor_id: '1',
    project_name: 'ME CAMPUSコーディング',
    amount_excl_tax: 850000,
    amount_incl_tax: 935000,
    invoice_month: '2024年10月',
    payment_month: '2024年11月',
    payment_status: '支払済',
    period: '第3期',
    notes: null,
    created_at: '2024-10-01',
  },
  {
    id: '2',
    contractor_id: '1',
    project_name: 'ココナラ開発',
    amount_excl_tax: 440000,
    amount_incl_tax: 484000,
    invoice_month: '2024年11月',
    payment_month: '2024年12月',
    payment_status: '未対応',
    period: '第3期',
    notes: null,
    created_at: '2024-11-01',
  },
  {
    id: '3',
    contractor_id: '2',
    project_name: 'AI Summit',
    amount_excl_tax: 60000,
    amount_incl_tax: 60000,
    invoice_month: '2024年10月',
    payment_month: '2024年11月',
    payment_status: '支払済',
    period: '第3期',
    notes: null,
    created_at: '2024-10-01',
  },
  {
    id: '4',
    contractor_id: '2',
    project_name: 'SassTOP＋下層3P＋AIサミット対応',
    amount_excl_tax: 254546,
    amount_incl_tax: 254546,
    invoice_month: '2024年11月',
    payment_month: '2024年12月',
    payment_status: '支払済',
    period: '第3期',
    notes: null,
    created_at: '2024-11-01',
  },
  {
    id: '5',
    contractor_id: '3',
    project_name: '関家具3サイト',
    amount_excl_tax: 200000,
    amount_incl_tax: 220000,
    invoice_month: '2024年11月',
    payment_month: '2024年12月',
    payment_status: '支払済',
    period: '第3期',
    notes: null,
    created_at: '2024-11-01',
  },
]
